admin_manage_publicite_index:
    path:     /
    defaults: { _controller: "NejmeddineBundle:Publicite:index" }
    methods:  GET

admin_manage_publicite_show:
    path:     /{id}/show
    defaults: { _controller: "NejmeddineBundle:Publicite:show" }
    methods:  GET

admin_manage_publicite_new:
    path:     /new
    defaults: { _controller: "NejmeddineBundle:Publicite:new" }
    methods:  [GET, POST]

admin_manage_publicite_edit:
    path:     /{id}/edit
    defaults: { _controller: "NejmeddineBundle:Publicite:edit" }
    methods:  [GET, POST]

admin_manage_publicite_delete:
    path:     /{id}/delete
    defaults: { _controller: "NejmeddineBundle:Publicite:delete" }
    methods:  DELETE
