admin_manage_reclamation_index:
    path:     /
    defaults: { _controller: "NejmeddineBundle:Reclamation:index" }
    methods:  GET

admin_manage_reclamation_show:
    path:     /{idReclamation}/show
    defaults: { _controller: "NejmeddineBundle:Reclamation:show" }
    methods:  GET

admin_manage_reclamation_new:
    path:     /new
    defaults: { _controller: "NejmeddineBundle:Reclamation:new" }
    methods:  [GET, POST]

admin_manage_reclamation_edit:
    path:     /{idReclamation}/edit
    defaults: { _controller: "NejmeddineBundle:Reclamation:edit" }
    methods:  [GET, POST]

admin_manage_reclamation_delete:
    path:     /{idReclamation}/delete
    defaults: { _controller: "NejmeddineBundle:Reclamation:delete" }
    methods:  DELETE
admin_manage_reclamation_changeetat:
    path:     /{idReclamation}/etat
    defaults: { _controller: "NejmeddineBundle:Reclamation:delete" }
    methods:  GET