hotel:
    path:     /hotel
    defaults: { _controller: FediFediBundle:hotel:hotel }
Pageaffichage:
    path:     admin/hotel/affichage
    defaults: { _controller: FediFediBundle:hotel:affichehotel }
ajout:
    path:     admin/hotel/Ajout
    defaults: { _controller: FediFediBundle:hotel:Ajout2 }
supp:
    path:     admin/hotel/Delete/{s}
    defaults: { _controller: FediFediBundle:hotel:Delete }
modif:
    path:     /hotel/Modifier/{s}
    defaults: { _controller: FediFediBundle:hotel:Modifier }
transport:
    path:     /transport
    defaults: { _controller: FediFediBundle:transport:transport }
ajouttransport:
    path:     /transport/AjoutT
    defaults: { _controller: FediFediBundle:transport:Ajout2 }
supptransport:
    path:     /DeleteT/{s}
    defaults: { _controller: FediFediBundle:transport:Delete }
modiftransport:
    path:     /transport/ModifierT/{s}
    defaults: { _controller: FediFediBundle:transport:Modifier }

hoteladmin:
    path:     /hoteladmin
    defaults: { _controller: FediFediBundle:reservationH:hoteladmin }
transportadmin:
    path:     /transportadmin
    defaults: { _controller: FediFediBundle:reservationT:transportadmin }
etatreshotel:
    path:     /etatreshotel/{s}
    defaults: { _controller: FediFediBundle:reservationH:modifier }