<?php

namespace Nesrine\JoueurBundle\Repository;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JoueurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyJoueur($nom){

        $query=$this->getEntityManager()
            ->createQuery("select j from NesrineJoueurBundle:Joueur j where  j.nomJ LIKE :nom")
            ->setParameter('nom',$nom.'%');
        return $query ->getResult();

    }
}
