
russia2_pi:
    resource: "@RUSSIA2PIBundle/Resources/config/routing.yml"
    prefix:   /

russiapi:
    resource: "@RUSSIAPIBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

Nejmeddine:
    resource: "@NejmeddineBundle/Resources/config/routing.yml"

Nesrine:
    resource: "@NesrineJoueurBundle/Resources/config/routing1.yml"
    prefix: /admin/manage/
Nesrine1:
    resource: "@NesrineJoueurBundle/Resources/config/routing.yml"
    prefix: /client/

fedic:
    resource: "@FediFediBundle/Resources/config/routing.yml"
    prefix: /client/
fedia:
    resource: "@FediFediBundle/Resources/config/routing1.yml"
    prefix: /admin/manage/
ticketroute:
    resource: "@TicketBundle/Resources/config/routing.yml"
WafaA:
    resource: "@ForumBundle/Resources/config/routing.yml"
WafaC:
    resource: "@ForumBundle/Resources/config/routingc.yml"