russia2_pi_homepage:
    path:     /client
    defaults: { _controller: "NejmeddineBundle:News:indexC" }
ViewArticle:
    path:     /client/news/{idNews}/show
    defaults: { _controller: "NejmeddineBundle:News:showNews" }
    methods:  GET
Reclamation:
    path:     /client/reclamation/new
    defaults: { _controller: "NejmeddineBundle:Reclamation:newfront" }
    methods:  [GET, POST]

