<?php

namespace TicketBundle\Repository;

/**
 * SituationEquipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituationEquipeRepository extends \Doctrine\ORM\EntityRepository
{
}
