News:
    path:     /news
    defaults: { _controller: NejmeddineBundle:News:AffichageNews }
modifierNews:
    path:     /modifiernews/{id}
    defaults: { _controller: NejmeddineBundle:News:modifierNews }