nejmeddine_admin_manage_news:
    resource: "@NejmeddineBundle/Resources/config/routing/news.yml"
    prefix:   /admin/manage/news
nejmeddine_admin_manage_reclamation:
    resource: "@NejmeddineBundle/Resources/config/routing/reclamation.yml"
    prefix:   /admin/manage/reclamation

