forum_topic:
    resource: "@ForumBundle/Resources/config/routing/topic.yml"
    prefix:   /admin/topic

forum_commentaire:
    resource: "@ForumBundle/Resources/config/routing/commentaire.yml"
    prefix:   /admin/commentaire

forum_post:
    resource: "@ForumBundle/Resources/config/routing/post.yml"
    prefix:   /admin/post


