Joueur:
    type: entity
    table: joueur
    indexes:
        NOM_EQUIPE:
            columns:
                - NOM_EQUIPE
    id:
        idJoueur:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_JOUEUR
            generator:
                strategy: IDENTITY
    fields:
        nomJ:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: NOM_J
        prenomJ:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: PRENOM_J
        nomEquipe:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: NOM_EQUIPE
        numeroJ:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: NUMERO_J
        nbbutsJ:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: NBBUTS_J
        emplacementJ:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: EMPLACEMENT_J
        photoJ:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: PHOTO_J
        appreciationJ:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: APPRECIATION_J
        nationaliteJ:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: NATIONALITE_J
    lifecycleCallbacks: {  }
