Probleme:
    type: entity
    table: probleme
    indexes:
        IDX_7AB2D714DABCD33D:
            columns:
                - idUser_prob
    id:
        idprobleme:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: idProbleme
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        niveaurequis:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: niveauRequis
        etatprobleme:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: EtatProbleme
        dateprobleme:
            type: datetime
            nullable: false
            column: dateProbleme
        secteur:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        valide:
            type: boolean
            nullable: false
        contenu:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        nbrcommentaireprobleme:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nbrCommentaireProbleme
        iduserProb:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: idUser_prob
        notificationadmin:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
