Transport:
    type: entity
    table: transport
    id:
        idTransport:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_TRANSPORT
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: TYPE
        depart:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: DEPART
        destination:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: DESTINATION
        dateDepart:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: DATE_DEPART
        dateArrivee:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: DATE_ARRIVEE
        nbrVoyageurs:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: NBR_VOYAGEURS
    lifecycleCallbacks: {  }
