<?php

namespace Fedi\FediBundle\Repository;

/**
 * HotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelRepository extends \Doctrine\ORM\EntityRepository
{
    public function SearchVille($ville){

        $query=$this->getEntityManager()
            ->createQuery("
        select v from FediFediBundle:Hotel v where  v.ville LIKE :ville
        ")

            ->setParameter('ville',$ville.'%');
        return $query ->getResult();

    }
}
