NejmeddineBundle\Entity\FollowUp:
    type: entity
    table: follow_up
    indexes:
        id_user_2:
            columns:
                - id_user
        author_2:
            columns:
                - author
    uniqueConstraints:
        id_user:
            columns:
                - id_user
        author:
            columns:
                - author
    id:
        idFollowup:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_FOLLOWUP
            generator:
                strategy: IDENTITY
    fields:
        dateFollow:
            type: date
            nullable: true
            column: DATE_FOLLOW
        statutFollow:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: STATUT_FOLLOW
        response:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: Response
    manyToOne:
        idUser:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_user:
                    referencedColumnName: id
            orphanRemoval: false
        author:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                author:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
