NejmeddineBundle\Entity\Match:
    type: entity
    table: match
    id:
        idMatch:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: id_match
            generator:
                strategy: IDENTITY
    fields:
        dateMatch:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: date_match
        heureMatch:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: heure_match
        duel:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Duel
        groupe:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: Groupe
        stade:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        nbrTicket:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: nbr_ticket
    lifecycleCallbacks: {  }
