NejmeddineBundle\Entity\Publicite:
    type: entity
    table: Publicite
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        url:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        startdatetime:
            type: date
            nullable: false
            column: startDatetime
        enddatetime:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: endDatetime
        prix:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: Prix
    lifecycleCallbacks: {  }
