NejmeddineBundle\Entity\Reclamation:
    type: entity
    table: reclamation
    indexes:
        FK_FAIRE:
            columns:
                - ID_UTILISATEUR
    uniqueConstraints:
        ID_UTILISATEUR:
            columns:
                - ID_UTILISATEUR
    id:
        idReclamation:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_RECLAMATION
            generator:
                strategy: IDENTITY
    fields:
        sujetRec:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: SUJET_REC
        descriptionRec:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
            column: DESCRIPTION_REC
        dateRec:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: DATE_REC
        etatRec:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ETAT_REC
    manyToOne:
        idUtilisateur:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_UTILISATEUR:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
