NejmeddineBundle\Entity\Reservation:
    type: entity
    table: reservation
    indexes:
        FK_CHOISIR:
            columns:
                - ID_HOTEL
        ID_UTILISATEUR:
            columns:
                - ID_UTILISATEUR
    id:
        idReservation:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID_RESERVATION
            generator:
                strategy: IDENTITY
    fields:
        idHotel:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: ID_HOTEL
        dateArrivee:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: DATE_ARRIVEE
        dateDepart:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: DATE_DEPART
        nbrNuit:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: NBR_NUIT
        type:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: TYPE
        nbrChambre:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: NBR_CHAMBRE
        nbrPersonne:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: NBR_PERSONNE
        etatReservation:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
                default: NON_CONFIRME
            column: ETAT_RESERVATION
    manyToOne:
        idUtilisateur:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ID_UTILISATEUR:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
